spring:
  application:
    name: game
  datasource:
    url: jdbc:postgresql://192.168.114.131:5432/bmdb
    username: bmuser
    password: 1234
    driver-class-name: org.postgresql.Driver

# MyBatis Configuration
# Locations of MyBatis mapper XML files
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true # mybatis ??? domain? ???? ? ??? ex) (SQL)USER_NO -> (Domain)userNo

# Server Info
server:
  port: 80